links:
  gh: https://github.com
  home: https://darii.net
  point-install: https://raw.githubusercontent.com/dariy/point/main/quickstart/install.sh
  point: https://point.darii.net
  # example: https://example.com
